### ISSUE TITLE
Follow guidelines for use of Passbolt registered trademark

### ISSUE THREAD

**Issue by stripthis** [shubhamdipt/passbolt-python-api#22]
Hello,

Thank you for this project. As the founder of passbolt wanted to reach out to you with regards to trademark use. 
Please have a look at the guidelines: https://www.passbolt.com/credits/trademark-guidelines

Feel free to reach out to us if you have questions!

**Comment by shubhamdipt** [comment]
Please let us know if certain changes are to be included.

**Comment by stripthis** [comment]
- Use a prominent notice to acknowledge Passbolt trademark, such as: E.g.: "Passbolt and the Passbolt logo are registered trademarks of Passbolt S.A.".
- Use a prominent notice to identify your affiliation, such as: “This project is a community driven project that is not associated with Passbolt S.A.”

**Comment by shubhamdipt** [comment]
Cool thanks. Is this sufficient? [Commit](https://github.com/shubhamdipt/passbolt-python-api/commit/ac03a42d1b1357691acc8655cfee14c73f91f259)

**Comment by stripthis** [comment]
Would be better at the top. Thanks,

**Comment by shubhamdipt** [comment]
Done. Please close this issue if you agree. Thanks

**Comment by stripthis** [comment]
Thanks a lot @shubhamdipt, much appreciated!
