### ISSUE TITLE
wrong dependency versions in package v0.3.5 distributed @ pypi

### ISSUE THREAD

**Issue by bbenno** [shubhamdipt/passbolt-python-api#28]
The current package version 0.3.5 distributed [at pypi](https://pypi.org/project/passbolt-python-api/0.3.5/) lacks the version updates of f004481013fed187eb88f68ba0da526c3130aded  
(i.e. loosening dependency constraints: `requests==2.26.0` → `requests>=2.26.0` and `typing-extensions==4.0.0` → `typing-extensions>=4.0.0`).

## Steps to reproduce / verify

1. Download [source distribution files](https://pypi.org/project/passbolt-python-api/0.3.5/#files) ([direct link](https://files.pythonhosted.org/packages/64/05/2957e09ad45c0d3c441d8009b451a5a9c42faf8c87e3d3b49a7c4f0b1b11/passbolt_python_api-0.3.5.tar.gz))
2. Inspect `passbolt_python_api-0.3.5/passbolt_python_api.egg-info/PKG-INFO` or `.../requires.txt`

Related: https://github.com/netzbegruenung/passbolt-salt/issues/7

**Comment by shubhamdipt** [comment]
Should be fixed now in 0.3.6 version.
